SCRIPTS=	veritawall.sh veritawall-import.sh veritawall-install.sh \
		veritawall-reset.sh veritawall-rootpass.sh veritawall-ufs.sh \
		veritawall-zfs.sh veritawall.subr.sh

MAN=		# not needed

PREFIX?=${DESTDIR}/usr

BINDIR=	${PREFIX}/libexec/bsdinstall

.include <bsd.prog.mk>
